name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile all C++ files
      run: |
        mkdir -p build
        g++ -Wall -Werror -o build/output *.cpp

    - name: Run compiled binary (optional)
      run: ./build/output
